/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function findMatchingFiles(patterns: Array<string>, maxDepth?: number | undefined | null, dir?: string | undefined | null, ignoreDirs?: Array<string> | undefined | null): Array<string>
export declare function readFileContent(filePath: string): string
