name: Create Release Notes
 
on:
  push:
    tags:
      - '*'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
 
    - name: Create Release Notes
      id: create_release_notes
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Changes in this release:
          - Includes all commits up to ${{ github.ref }}